### ISSUE TITLE
Set up .github folder

### ISSUE THREAD

**Issue by dorianjagusch** [dorianjagusch/ft_transcendence#2]
**Description**:
 Describe the task that needs to be done. Most typically a sub task to a milestone or another larger task that best has an ordered set of subproblems. 

**Milestone/issue**:
 - [ ] Create template files #1 

  - [ ] Create workflow files for Linting #3
    - [ ] JS
    - [ ] Python
  - [ ] Create workflow files for Testing
    - [ ] Unit tests
      - [ ] JS
      - [ ] Python
    - [ ] Integration tests
      - [ ] JS
      - [ ] Python
    - [ ] E2E tests
      - [ ] JS
      - [ ] Python
