### ISSUE TITLE
Frontend responsiveness

### ISSUE THREAD

**Issue by dorianjagusch** [dorianjagusch/ft_transcendence#39]
**Description**:
The current frontend pages are not fully responsive. In the end we just need to have the pages working on a large screen, but during development it's nice when the page doesn't look disheveled.

**Tasks**
- [ ] Landing page responsiveness
- [ ] Login page  responsiveness
- [ ] Register page  responsiveness
- [ ] Friend page responsiveness
- [ ] notification wrap responsiveness
- [ ] userCard responsiveness
- [ ] ProfilePage responsiveness
